# Generated by Django 5.0.7 on 2024-08-10 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="payment",
            old_name="pay_mothod",
            new_name="pay_method",
        ),
    ]
