# Generated by Django 5.0.7 on 2024-07-28 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "image_preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="materials/",
                        verbose_name="Изображение (превью)",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Опишите курс", verbose_name="Описание"),
                ),
            ],
            options={
                "verbose_name": "Курс",
                "verbose_name_plural": "Курсы",
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Укажите название",
                        max_length=100,
                        verbose_name="Название",
                    ),
                ),
                (
                    "image_preview",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="materials/",
                        verbose_name="Изображение (превью)",
                    ),
                ),
                (
                    "description",
                    models.TextField(help_text="Опишите урок", verbose_name="Описание"),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Укажите ссылку на видео",
                        max_length=300,
                        null=True,
                        verbose_name="Ссылка на видео",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="materials.course",
                        verbose_name="Курс",
                    ),
                ),
            ],
            options={
                "verbose_name": "Урок",
                "verbose_name_plural": "Уроки",
            },
        ),
    ]
