# Generated by Django 5.0.7 on 2024-08-05 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="image_preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="materials/photo",
                verbose_name="Изображение (превью)",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="image_preview",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="materials/photo",
                verbose_name="Изображение (превью)",
            ),
        ),
    ]
